version: "3.8"
services:
 frontend:
    image: "infracloudio/csvserver:latest"
    ports:
      - 9393:9300
    volumes:
      - /home/centos/infracloud/solution/csvserver/solution/inputFile:/csvserver/inputdata:z
    environment:
      CSVSERVER_BORDER: Orange
    command: ["/csvserver/csvserver"]
